name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_STORAGE_URL: ${{ secrets.AZURE_STORAGE_URL }}
          AZURE_SECRET_NAME: ${{ secrets.AZURE_SECRET_NAME }}
        run: git push --force https://hf-nikhil:$HF_TOKEN@huggingface.co/spaces/hf-nikhil/news-articles-sorting main